env:
  node: true
extends:
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
ignorePatterns:
  - 'index.js'
  - 'index.d.ts'
  - 'coverage'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2018
  project: ./tsconfig.json
plugins:
  - '@typescript-eslint'
